SELECT 
    phi_van_chuyen_thuc_te,
    phi_van_chuyen_tro_gia_tu_san,
    phi_thanh_toan,
    phi_hoa_hong_shop,
    phi_hoa_hong_tiep_thi_lien_ket,
    phi_hoa_hong_quang_cao_cua_hang,
    phi_dich_vu,
    phi_xtra,
    voucher_from_seller,
    phi_co_dinh,
    tien_khach_hang_thanh_toan,
    tien_sp_sau_tro_gia,
    phi_ship,
    giam_gia_seller,
    giam_gia_san,
    seller_tro_gia,
    san_tro_gia,
    tong_phi_san,
    brand,
    CAST(ma_don_hang AS string) AS ma_don_hang,
    ngay_tao_don,
    sku_code,
    ten_san_pham,
    CAST(so_luong AS INT64) AS so_luong,
    status,
    status_dang_don,
    gia_san_pham_goc,
    gia_san_pham_goc_total,
    gia_ban_daily,
    gia_ban_daily_total,
    tien_chiet_khau_sp,
    doanh_thu_ke_toan,
    'Facebook' AS channel,
    company,
    customer_name AS ten_khach_hang
FROM {{ ref('t2_facebook_order_lines_toa') }} where company = 'One5'

UNION ALL

SELECT 
    phi_van_chuyen_thuc_te,
    phi_van_chuyen_tro_gia_tu_san,
    phi_thanh_toan,
    phi_hoa_hong_shop,
    phi_hoa_hong_tiep_thi_lien_ket,
    phi_hoa_hong_quang_cao_cua_hang,
    phi_dich_vu,
    phi_xtra,
    voucher_from_seller,
    phi_co_dinh,
    tien_khach_hang_thanh_toan,
    tien_sp_sau_tro_gia,
    phi_ship,
    giam_gia_seller,
    giam_gia_san,
    seller_tro_gia,
    san_tro_gia,
    tong_phi_san,
    brand,
    CAST(ma_don_hang AS string) AS ma_don_hang,
    ngay_tao_don,
    sku_code,
    ten_san_pham,
    CAST(so_luong AS INT64) AS so_luong,
    status,
    '' as status_dang_don,
    gia_san_pham_goc,
    gia_san_pham_goc_total,
    gia_ban_daily,
    gia_ban_daily_total,
    tien_chiet_khau_sp,
    doanh_thu_ke_toan,
    'Shopee' AS channel,
    company,
    ten_nguoi_mua AS ten_khach_hang
FROM {{ ref('t2_shopee_order_lines_toa') }} where company = 'One5'

UNION ALL

SELECT 
    phi_van_chuyen_thuc_te,
    phi_van_chuyen_tro_gia_tu_san,
    phi_thanh_toan * -1,
    phi_hoa_hong_shop * -1,
    phi_hoa_hong_tiep_thi_lien_ket * -1,
    phi_hoa_hong_quang_cao_cua_hang,
    phi_dich_vu * -1,
    phi_xtra * -1,
    voucher_from_seller,
    phi_co_dinh * -1,
    tien_khach_hang_thanh_toan,
    tien_sp_sau_tro_gia,
    phi_ship,
    giam_gia_seller,
    giam_gia_san,
    seller_tro_gia,
    san_tro_gia,
    tong_phi_san * -1,
    brand,
    CAST(ma_don_hang AS string) AS ma_don_hang,
    ngay_tao_don,
    sku_code,
    ten_san_pham,
    CAST(so_luong AS INT64) AS so_luong,
    status,
    '' as status_dang_don,
    gia_san_pham_goc,
    gia_san_pham_goc_total,
    gia_ban_daily,
    gia_ban_daily_total,
    tien_chiet_khau_sp,
    doanh_thu_ke_toan,
    'Tiktok' AS channel,
    company,
    Recipient AS ten_khach_hang
FROM {{ ref('t2_tiktok_order_line_toa') }} where company = 'One5'

