select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'One5' as company,
    '8750459938-888' as tax_code,
    'Chaching' as brand,
    'Chaching Brand' as shop,
    '1360134442' as shop_id
from `chaching_shopee_shop_dwh.shopee_payment_escrow_detail_chaching_brand`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'One5' as company,
    '0317423004' as tax_code,
    'LYB' as brand,
    'LYB Official' as shop,
    '847813660' as shop_id
from `lyb_shopee_shop_dwh.shopee_payment_escrow_detail_lyb_official`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'One5' as company,
    '0317468051' as tax_code,
    'An Cung' as brand,
    'An Cung Brand' as shop,
    '1442362266' as shop_id
from `ancung_shopee_shop_dwh.shopee_payment_escrow_detail_ancung_brand`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '0317423004' as tax_code,
    'LYB Cosmetics' as brand,
    'LYB Cosmetics' as shop,
    '1266788038' as shop_id
from `lybcosmetic_shopee_shop_dwh.shopee_payment_escrow_detail_lyb_cosmetic`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'One5' as company,
    '0315027453' as tax_code,
    'UME' as brand,
    'UME Viet Nam' as shop,
    '1023530981' as shop_id
from `ume_shopee_shop_dwh.shopee_payment_escrow_detail_ume_viet_nam`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'One5' as company,
    '-' as tax_code,
    'Omazo' as brand,
    'omazo_vietnam' as shop,
    'omazo_vietnam' shop_id
from `omazo_shopee_shop_dwh.shopee_payment_escrow_detail_omazo_vietnam`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'One5' as company,
    '-' as tax_code,
    'Dr Diva' as brand,
    'dr_diva_viet_nam' as shop,
    'dr_diva_viet_nam' as shop_id
from `drdiva_shopee_shop_dwh.shopee_payment_escrow_detail_dr_diva_viet_nam`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'One5' as company,
    '-' as tax_code,
    'Chaching Beauty' as brand,
    'Chaching Beauty' as shop,
    '1569014047' as shop_id
from `chaching_beauty_shopee_shop_dwh.shopee_payment_escrow_detail_chaching_beauty`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'One5' as company,
    '-' as tax_code,
    'LYB' as brand,
    'LYB Fashion' as shop,
    '1648366043' as shop_id
from `lybfashion_shopee_shop_dwh.shopee_payment_escrow_detail_lyb_fashion`

union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'BE20' as brand,
    'BE20 kẹo ngậm trắng da' as shop,
    '1333711265' as shop_id
from
    `be20keongamdautamtrangda_shopee_shop_dwh.shopee_payment_escrow_detail_be20_keo_ngam_trang_da`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Cà Phê Mâm Xôi' as brand,
    'Cà phê mâm xôi chính hãng' as shop,
    '1333711265' as shop_id
from
    `be20keongamdautamtrangda_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_mam_xoi_chinh_hang`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'UME' as brand,
    'belle_beauty_vietnam_sp' as shop,
    'belle_beauty_vietnam_sp' as shop_id
from
    `bellebeautyvietnam_shopee_shop_dwh.shopee_payment_escrow_detail_belle_beauty_vietnam`
-- UNION ALL
-- SELECT order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name,
-- items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee,
-- shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee,
-- instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as
-- company, '-' AS tax_code, 'Belle Beauty' AS brand, 'belle_vietnam_store' AS shop
-- FROM
-- `bellevietnamstore_shopee_shop_dwh.shopee_payment_escrow_detail_belle_vietnam_store`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Cà phê gừng' as brand,
    'ca_phe_giam_can_store' as shop,
    'ca_phe_giam_can_store' as shop_id
from
    `caphegiamcanstore_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_giam_can_store`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Cà phê gừng' as brand,
    'ca_phe_gung_mat_ong_giam_can' as shop,
    'ca_phe_gung_mat_ong_giam_can' as shop_id
from
    `caphegungmatonggiamcan_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_gung_mat_ong_giam_can`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Cà phê gừng' as brand,
    'tong_cong_ty_ca_phe_giam_can' as shop,
    'tong_cong_ty_ca_phe_giam_can' as shop_id
from
    `tongcongtycaphegiamcan_shopee_shop_dwh.shopee_payment_escrow_detail_tong_cong_ty_ca_phe_giam_can`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Cà Phê Mâm Xôi' as brand,
    'cafe_mam_xoi_viet_nam' as shop,
    'cafe_mam_xoi_viet_nam' as shop_id
from
    `caphemamxoivietnam_shopee_shop_dwh.shopee_payment_escrow_detail_cafe_mam_xoi_viet_nam`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Cà Phê Mâm Xôi' as brand,
    'ca_phe_mam_xoi_chinh_hang' as shop,
    'ca_phe_mam_xoi_chinh_hang' as shop_id
from
    `caphemamxoichinhhang_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_mam_xoi_chinh_hang`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'BE20' as brand,
    'keo_ngam_trang_da_dau_tam_be20' as shop,
    'keo_ngam_trang_da_dau_tam_be20' as shop_id
from
    `keongamtrangdadautambe20_shopee_shop_dwh.shopee_payment_escrow_detail_keo_ngam_trang_da_dau_tam_be20`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Cà Phê Mâm Xôi' as brand,
    'raspberry_coffee_offlclal' as shop,
    'raspberry_coffee_offlclal' as shop_id
from
    `raspberrycoffeeofficial_shopee_shop_dwh.shopee_payment_escrow_detail_raspberry_coffee_offlclal`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'UME' as brand,
    'nhat_dang_nhi_da_store' as shop,
    'nhat_dang_nhi_da_store' as shop_id
from
    `nhatdangnhidastore_shopee_shop_dwh.shopee_payment_escrow_detail_nhat_dang_nhi_da_store`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Cà Phê Mâm Xôi' as brand,
    'ca_phe_mam_xoi_chinh_hang' as shop,
    'ca_phe_mam_xoi_chinh_hang' as shop_id
from
    `caphemamxoichinhhang2_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_mam_xoi_chinh_hang`
union all
select
    final_shipping_fee,
    estimated_shipping_fee,
    0 as withholding_pit_tax,
    0 as withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Dr Diva' as brand,
    'dr_diva_beauty_store' as shop,
    'dr_diva_beauty_store' as shop_id
from
    `drdivabeautystore_shopee_shop_dwh.shopee_payment_escrow_detail_dr_diva_beauty_store`

union all

select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'UME' as brand,
    'the_ume_lab' as shop,
    'the_ume_lab' as shop_id
from `theumelab_shopee_shop_dwh.shopee_payment_escrow_detail_the_ume_lab`

union all

select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'BE20' as brand,
    'BE20 Việt Nam Store' as shop,
    '1414505993' as shop_id
from `be20vietnamstore_shopee_shop_dwh.shopee_payment_escrow_detail_be20_viet_nam_store`

union all

select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'UME' as brand,
    'UME Beauty VN' as shop,
    '1601895285' as shop_id
from `umebeautyvietnam_shope_shop_dwh.shopee_payment_escrow_detail_ume_beauty_vietnam`

union all

select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'BE20' as brand,
    'Beana beauty VietNam' as shop,
    '216095138' as shop_id
from
    `beanabeautyvietnam_shopee_shop_dwh.shopee_payment_escrow_detail_beana_beauty_vietnam`

union all

select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Cà Phê Mâm Xôi' as brand,
    'Cà phê mâm xôi store' as shop,
    '216095138' as shop_id
from
    `beanabeautyvietnam_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_mam_xoi_store`

union all

select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Dr Diva' as brand,
    'Las Beauty' as shop,
    '1506821514' as shop_id
from `ancunghaircare_shopee_shop_dwh.shopee_payment_escrow_detail_las_beauty`

union all

select
    final_shipping_fee,
    estimated_shipping_fee,
    withholding_pit_tax,
    withholding_vat_tax,
    reverse_shipping_fee,
    final_return_to_seller_shipping_fee,
    rsf_seller_protection_fee_claim_amount,
    order_id,
    voucher_from_seller,
    buyer_paid_shipping_fee,
    buyer_user_name,
    items,
    commission_fee,
    service_fee,
    seller_transaction_fee,
    actual_shipping_fee,
    shopee_shipping_rebate,
    credit_card_promotion,
    order_ams_commission_fee,
    instalment_plan,
    seller_voucher_code,
    seller_shipping_discount,
    'Max Eagle' as company,
    '-' as tax_code,
    'Chanh tây' as brand,
    'Lemon Coffee' as shop,
    '1662596872' as shop_id
from
    `lemoncoffee_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_chanh_tay_lemon_coffee`
