SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'One5' as company, '8750459938-888' AS tax_code, 'Chaching' AS brand, 'chaching_brand' AS shop
FROM `chaching_shopee_shop_dwh.shopee_payment_escrow_detail_chaching_brand`
UNION ALL
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'One5' as company,  '0317423004' AS tax_code, 'LYB' AS brand, 'lyb_official' AS shop
FROM `lyb_shopee_shop_dwh.shopee_payment_escrow_detail_lyb_official`
UNION ALL
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'One5' as company,  '0317468051' AS tax_code, 'An Cung' AS brand, 'ancung_brand' AS shop
FROM `ancung_shopee_shop_dwh.shopee_payment_escrow_detail_ancung_brand`
UNION ALL
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'Max Eagle' as company,  '0317423004' AS tax_code, 'LYB Cosmetics' AS brand, 'lyb_cosmetic_sp' AS shop
FROM `lybcosmetic_shopee_shop_dwh.shopee_payment_escrow_detail_lyb_cosmetic`
UNION ALL
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'One5' as company,  '0315027453' AS tax_code, 'UME' AS brand, 'ume_viet_nam' AS shop
FROM `ume_shopee_shop_dwh.shopee_payment_escrow_detail_ume_viet_nam`
UNION ALL
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'One5' as company,  '-' AS tax_code, 'Omazo' AS brand, 'omazo_vietnam' AS shop
FROM `omazo_shopee_shop_dwh.shopee_payment_escrow_detail_omazo_vietnam`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'One5' as company,  '-' AS tax_code, 'Dr Diva' AS brand, 'dr_diva_viet_nam' AS shop
FROM `drdiva_shopee_shop_dwh.shopee_payment_escrow_detail_dr_diva_viet_nam`
UNION ALL
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'One5' as company,  '-' AS tax_code, 'Chaching Beauty' AS brand, 'chaching_beauty' AS shop
FROM `chaching_beauty_shopee_shop_dwh.shopee_payment_escrow_detail_chaching_beauty` 
UNION ALL
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'Max Eagle' as company,  '-' AS tax_code, 'BE20' AS brand, 'be20_keo_ngam_trang_da_sp' AS shop
FROM `be20keongamdautamtrangda_shopee_shop_dwh.shopee_payment_escrow_detail_be20_keo_ngam_trang_da`
UNION ALL
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as company, '-' AS tax_code, 'UME' AS brand, 'belle_beauty_vietnam_sp' AS shop
FROM `bellebeautyvietnam_shopee_shop_dwh.shopee_payment_escrow_detail_belle_beauty_vietnam`
-- UNION ALL
-- SELECT order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as company, '-' AS tax_code, 'Belle Beauty' AS brand, 'belle_vietnam_store' AS shop
-- FROM `bellevietnamstore_shopee_shop_dwh.shopee_payment_escrow_detail_belle_vietnam_store`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as company, '-' AS tax_code, 'Cà phê gừng' AS brand, 'ca_phe_giam_can_store' AS shop
FROM `caphegiamcanstore_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_giam_can_store`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as company, '-' AS tax_code, 'Cà phê gừng' AS brand, 'ca_phe_gung_mat_ong_giam_can' AS shop
FROM `caphegungmatonggiamcan_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_gung_mat_ong_giam_can`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as company, '-' AS tax_code, 'Cà phê gừng' AS brand, 'tong_cong_ty_ca_phe_giam_can' AS shop
FROM `tongcongtycaphegiamcan_shopee_shop_dwh.shopee_payment_escrow_detail_tong_cong_ty_ca_phe_giam_can`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as company, '-' AS tax_code, 'Cà Phê Mâm Xôi' AS brand, 'cafe_mam_xoi_viet_nam' AS shop
FROM `caphemamxoivietnam_shopee_shop_dwh.shopee_payment_escrow_detail_cafe_mam_xoi_viet_nam`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as company, '-' AS tax_code, 'Cà Phê Mâm Xôi' AS brand, 'ca_phe_mam_xoi_chinh_hang' AS shop
FROM `caphemamxoichinhhang_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_mam_xoi_chinh_hang`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as company, '-' AS tax_code, 'BE20' AS brand, 'keo_ngam_trang_da_dau_tam_be20' AS shop
FROM `keongamtrangdadautambe20_shopee_shop_dwh.shopee_payment_escrow_detail_keo_ngam_trang_da_dau_tam_be20`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as company, '-' AS tax_code, 'Cà Phê Mâm Xôi' AS brand, 'raspberry_coffee_offlclal' AS shop
FROM `raspberrycoffeeofficial_shopee_shop_dwh.shopee_payment_escrow_detail_raspberry_coffee_offlclal`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount, 'Max Eagle' as company, '-' AS tax_code, 'UME' AS brand, 'nhat_dang_nhi_da_store' AS shop
FROM `nhatdangnhidastore_shopee_shop_dwh.shopee_payment_escrow_detail_nhat_dang_nhi_da_store`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'Max Eagle' as company,  '-' AS tax_code, 'Cà Phê Mâm Xôi' AS brand, 'ca_phe_mam_xoi_chinh_hang' AS shop
FROM `caphemamxoichinhhang2_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_mam_xoi_chinh_hang`
UNION ALL
SELECT 0 as withholding_pit_tax, 0 as withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'Max Eagle' as company,  '-' AS tax_code, 'Dr Diva' AS brand, 'dr_diva_beauty_store' AS shop
FROM `drdivabeautystore_shopee_shop_dwh.shopee_payment_escrow_detail_dr_diva_beauty_store`
UNION ALL
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'Max Eagle' as company,  '-' AS tax_code, 'UME' AS brand, 'the_ume_lab' AS shop
FROM `theumelab_shopee_shop_dwh.shopee_payment_escrow_detail_the_ume_lab`
union all
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'Max Eagle' as company,  '-' AS tax_code, 'BE20' AS brand, 'be20_viet_nam_store_sp' AS shop
FROM `be20vietnamstore_shopee_shop_dwh.shopee_payment_escrow_detail_be20_viet_nam_store`
union all
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'Max Eagle' as company,  '-' AS tax_code, 'UME' AS brand, 'ume_beauty_vietnam_sp' AS shop
FROM `umebeautyvietnam_shope_shop_dwh.shopee_payment_escrow_detail_ume_beauty_vietnam`
union all
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'Max Eagle' as company,  '-' AS tax_code, 'BE20' AS brand, 'beana_beauty_vietnam_sp' AS shop
FROM `beanabeautyvietnam_shopee_shop_dwh.shopee_payment_escrow_detail_beana_beauty_vietnam`
union all
SELECT withholding_pit_tax, withholding_vat_tax, reverse_shipping_fee, final_return_to_seller_shipping_fee, rsf_seller_protection_fee_claim_amount, order_id, voucher_from_seller, buyer_paid_shipping_fee, buyer_user_name, items, commission_fee, service_fee, seller_transaction_fee, actual_shipping_fee, shopee_shipping_rebate, credit_card_promotion, order_ams_commission_fee, instalment_plan, seller_voucher_code, seller_shipping_discount,'Max Eagle' as company,  '-' AS tax_code, 'An Cung' AS brand, 'las_beauty' AS shop
FROM `ancunghaircare_shopee_shop_dwh.shopee_payment_escrow_detail_las_beauty`




