select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '8750459938-888' as tax_code ,'Chaching' as brand from `chaching_shopee_shop_dwh.shopee_payment_escrow_detail_chaching_brand`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '0317423004' as tax_code ,'LYB' as brand from `lyb_shopee_shop_dwh.shopee_payment_escrow_detail_lyb_official`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '0317468051' as tax_code ,'An Cung' as brand from `ancung_shopee_shop_dwh.shopee_payment_escrow_detail_ancung_brand`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '0317423004' as tax_code ,'LYB Cosmetics' as brand from `lybcosmetic_shopee_shop_dwh.shopee_payment_escrow_detail_lyb_cosmetic`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '0315027453' as tax_code ,'UME' as brand from `ume_shopee_shop_dwh.shopee_payment_escrow_detail_ume_viet_nam`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'BE20(kẹo ngậm)' as brand from `be20keongamdautamtrangda_shopee_shop_dwh.shopee_payment_escrow_detail_be20_keo_ngam_dau_tam_trang_da`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'Belle Beauty' as brand from `bellebeautyvietnam_shopee_shop_dwh.shopee_payment_escrow_detail_belle_beauty_vietnam`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'Belle Beauty' as brand from `bellevietnamstore_shopee_shop_dwh.shopee_payment_escrow_detail_belle_vietnam_store`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'Cà phê gừng' as brand from `caphegiamcanstore_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_giam_can_store`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'Cà phê gừng' as brand from `caphegungmatonggiamcan_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_gung_mat_ong_giam_can`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'Cà phê gừng' as brand from `tongcongtycaphegiamcan_shopee_shop_dwh.shopee_payment_escrow_detail_tong_cong_ty_ca_phe_giam_can`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'Cà phê mâm xôi' as brand from `caphemamxoivietnam_shopee_shop_dwh.shopee_payment_escrow_detail_cafe_mam_xoi_viet_nam`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'Cà phê mâm xôi' as brand from `caphemamxoichinhhang_shopee_shop_dwh.shopee_payment_escrow_detail_ca_phe_mam_xoi_chinh_hang`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'BE20(kẹo ngậm)' as brand from `keongamtrangdadautambe20_shopee_shop_dwh.shopee_payment_escrow_detail_keo_ngam_trang_da_dau_tam_be20`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'Cà phê mâm xôi' as brand from `raspberrycoffeeofficial_shopee_shop_dwh.shopee_payment_escrow_detail_raspberry_coffee_offlclal`
union all
select order_id,voucher_from_seller,buyer_paid_shipping_fee,buyer_user_name,items,commission_fee,service_fee,seller_transaction_fee,actual_shipping_fee,shopee_shipping_rebate,credit_card_promotion,order_ams_commission_fee, instalment_plan,seller_voucher_code, seller_shipping_discount, '-' as tax_code ,'UME' as brand from `nhatdangnhidastore_shopee_shop_dwh.shopee_payment_escrow_detail_nhat_dang_nhi_da_store`






