SELECT 'One5' as company, 'An Cung' AS brand, 'an_cung_brand' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `ancung_tiktok_shop_dwh.tiktok_shop_an_cung_brand_order`
UNION ALL 
SELECT 'One5' as company, 'Chaching' AS brand, 'chaching_brand' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `chaching_tiktok_shop_dwh.tiktok_shop_chaching_brand_order`
UNION ALL
SELECT 'One5' as company, 'Chaching' AS brand, 'cha_ching_fashion' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `chaching_2_tiktok_shop_dwh.tiktok_shop_cha_ching_fashion_order`
UNION ALL
SELECT 'One5' as company, 'LYB' AS brand, 'lyb_brand' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `lyb_tiktok_shop_dwh.tiktok_shop_lyb_brand_order`
-- UNION ALL
-- SELECT 'Max Eagle' as company, 'LYB Cosmetics' AS brand, 'lyb_cosmetic_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note FROM `lybcosmetic_tiktok_shop_dwh.tiktok_shop_lyb_cosmetic_order`
UNION ALL
SELECT 'One5' as company, 'UME' AS brand, 'ume_viet_nam' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `ume_tiktok_shop_dwh.tiktok_shop_ume_viet_nam_order`
UNION ALL
SELECT 'One5' as company, 'Omazo' AS brand, 'omazo_vietnam' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `omazo_tiktok_shop_dwh.tiktok_shop_omazo_vietnam_order`
UNION ALL
SELECT 'One5' as company, 'Chaching Beauty' AS brand, 'cha_ching_beauty' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `chaching_beauty_tiktok_shop_dwh.tiktok_shop_cha_ching_beauty_order`
UNION ALL
SELECT 'One5' as company, 'UME' AS brand, 'cham_soc_lan_da_trang_min' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `chamsoclandatrangmin_tiktok_shop_dwh.tiktok_shop_cham_soc_lan_da_trang_min_order`
-- union all
-- SELECT 'Max Eagle' as company, 'UME' AS brand, 'belle_viet_nam_store_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note FROM `bellevietnamstore_tiktok_shop_dwh.tiktok_shop_belle_viet_nam_store_order`
UNION ALL
-- SELECT 'Max Eagle' as company, 'Cà Phê Mâm Xôi' AS brand, 'cafe_mam_xoi_chinh_hang_store' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note FROM `caphemamxoichinhhangstore_tiktok_shop_dwh.tiktok_shop_cafe_mam_xoi_chinh_hang_store_order`
-- UNION ALL
-- SELECT 'Max Eagle' as company, 'Cà Phê Mâm Xôi' AS brand, 'ca_phe_mam_xoi_store' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note FROM `caphemamxoistore_tiktok_shop_dwh.tiktok_shop_ca_phe_mam_xoi_store_order`
-- UNION ALL
-- SELECT 'Max Eagle' as company, 'Cà Phê Mâm Xôi' AS brand, 'cafe_mam_xoi_store_hcm' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note FROM `caphemamxoistorehcm_tiktok_shop_dwh.tiktok_shop_cafe_mam_xoi_store_hcm_order`
-- UNION ALL
-- SELECT 'Max Eagle' as company, 'Cà Phê Mâm Xôi' AS brand, 'raspberry_coffee_store' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note FROM `raspberrycoffeestore_tiktok_shop_dwh.tiktok_shop_raspberry_coffee_store_order`
-- UNION ALL


--code sử dụng
SELECT 'Max Eagle' as company, 'LYB Cosmetics' AS brand, 'lyb_beauty_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `lybbeauty_tiktok_shop_dwh.tiktok_shop_lyb_beauty_order`
UNION ALL 
SELECT 'Max Eagle' as company, 'BE20' AS brand, 'be20_viet_nam_store_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `be20vietnamstore_tiktok_shop_dwh.tiktok_shop_be20_viet_nam_store_order`
UNION ALL 
SELECT 'Max Eagle' as company, 'BE20' AS brand, 'be20_viet_nam_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `be20vietnam3_tiktok_shop_dwh.tiktok_shop_be20_viet_nam_order`
-- UNION ALL 
-- SELECT 'Max Eagle' as company, 'BE20' AS brand, 'be20_viet_nam_store_2' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note FROM `be20vietnam2_tiktok_shop_dwh.tiktok_shop_be20_viet_nam_store_order`
UNION ALL 
SELECT 'Max Eagle' as company, 'UME' AS brand, 'ume_beauty_natural_viet_nam_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `umebeautynaturalvn_tiktok_shop_dwh.tiktok_shop_the_ume_lab_order`
UNION ALL 
-- SELECT 'Max Eagle' as company, 'UME' AS brand, 'ume_beauty_vietnam_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `umebeautyvietnam_tiktok_shop_dwh.tiktok_shop_ume_beauty_vietnam_order`
-- UNION ALL 
SELECT 'Max Eagle' as company, 'UME' AS brand, 'ume_beauty_vietnam_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `umebeautyvietnam_tiktok_shop_dwh.tiktok_shop_ume_beauty_vietnam_order`
UNION ALL 
SELECT 'Max Eagle' as company, 'LYB Cosmetics' AS brand, 'lyb_cosmetic_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `lybcosmeticvn_tiktok_shop_dwh.tiktok_shop_lyb_cosmetic_order`
UNION ALL 
SELECT 'Max Eagle' as company, 'UME' AS brand, 'belle_store_vn_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `bellestorevn_tiktok_shop_dwh.tiktok_shop_belle_store_vn_order`
UNION ALL 
SELECT 'Max Eagle' as company, 'Dr Diva' AS brand, 'dr_diva_viet_nam_store_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `drdivavietnamstore_tiktok_shop_dwh.tiktok_shop_dr_diva_viet_nam_store_order`
UNION ALL 
SELECT 'Max Eagle' as company, 'Cà Phê Mâm Xôi' AS brand, 'ca_phe_mam_xoi_shop_tt' AS shop, order_id,line_items,order_status,payment,create_time,paid_time,rts_time,collection_time,delivery_time,cancel_time,cancellation_initiator,fulfillment_type,warehouse_id,tracking_number,delivery_option_name,shipping_provider,buyer_message,buyer_email,recipient_address,payment_method_name,seller_note,order_type FROM `caphemamxoishop_tiktok_shop_dwh.tiktok_shop_ca_phe_mam_xoi_shop_order`

--end