select 
brand,
''as ma_giao_dich,
'Order' as don_hang_san_pham,
order_id,
ma_so_thue,
ma_yeu_cau_hoan_tien,
'-' as ma_san_pham,
'-' as ten_san_pham,
ngay_dat_hang,
ngay_hoan_thanh_thanh_toan,
phuong_thuc_thanh_toan,
loai_don_hang,
SUM(tong_tien_da_thanh_toan) AS tong_tien_da_thanh_toan,
SUM(tong_tien_san_pham) AS tong_tien_san_pham,
SUM(so_tien_hoan_lai) AS so_tien_hoan_lai,
SUM(phi_van_chuyen_nguoi_mua_tra) AS phi_van_chuyen_nguoi_mua_tra,
SUM(phi_van_chuyen_thuc_te) AS phi_van_chuyen_thuc_te,
SUM(phi_van_chuyen_tro_gia_tu_shopee) AS phi_van_chuyen_tro_gia_tu_shopee,
SUM(phi_tra_hang) AS phi_tra_hang,
SUM(phi_van_chuyen_duoc_hoan_tien) AS phi_van_chuyen_duoc_hoan_tien,
SUM(phi_tra_hang_cho_nguoi_ban) AS phi_tra_hang_cho_nguoi_ban,
SUM(tro_gia_tu_shopee) AS tro_gia_tu_shopee,
SUM(ma_giam_gia) AS ma_giam_gia,
SUM(nguoi_ban_hoan_xu) AS nguoi_ban_hoan_xu,
SUM(phi_co_dinh) AS phi_co_dinh,
SUM(phi_dich_vu) AS phi_dich_vu,
SUM(phi_thanh_toan) AS phi_thanh_toan,
SUM(phi_hoa_hong_tiep_thi_lien_ket) AS phi_hoa_hong_tiep_thi_lien_ket,
SUM(phi_dich_vu_piship) AS phi_dich_vu_piship,
thue_gtgt,
thue_tncn,
SUM(buyer_paid_installation_fee) AS buyer_paid_installation_fee,
SUM(actual_installition_fee) AS actual_installition_fee,
ten_nguoi_mua,
SUM(amount_paid_by_buyer) AS amount_paid_by_buyer,
5 AS transaction_fee_rate,
phuong_thuc_thanh_toan_nguoi_mua,
buyer_payment_method_details_1,
installment_plan,
SUM(phi_van_chuyen_seller_support) AS phi_van_chuyen_seller_support,
ten_don_vi_van_chuyen,
couruer_name,
voucher_code,
den_bu_don_mat_hang,
SUM(gia_san_pham_sau_khuyen_mai) AS gia_san_pham_sau_khuyen_mai,
SUM(shopee_xu) AS shopee_xu,
SUM(shopee_voucher) AS shopee_voucher,
SUM(ngan_hang_khuyen_mai_the_tin_dung) AS ngan_hang_khuyen_mai_the_tin_dung,
SUM(shopee_khuyen_mai_the_tin_dung) AS shopee_khuyen_mai_the_tin_dung
from `dtm.t2_shopee_order_lines_tot`
group by order_id, ngay_dat_hang, ngay_hoan_thanh_thanh_toan, phuong_thuc_thanh_toan, loai_don_hang, ma_giao_dich, ma_so_thue, ma_yeu_cau_hoan_tien, thue_gtgt, thue_tncn, ten_nguoi_mua, phuong_thuc_thanh_toan_nguoi_mua, transaction_fee_rate, buyer_payment_method_details_1, installment_plan, ten_don_vi_van_chuyen, couruer_name, voucher_code, den_bu_don_mat_hang, brand