SELECT 
    ''as ma_giao_dich,
    'Order' as don_hang_san_pham,
    vi.order_id,
    ''as ma_so_thue,
    ''as ma_yeu_cau_hoan_tien,
    '-' as ma_san_pham,
    '-' as ten_san_pham,
    vi.amount as test_doanh_thu,
    ord.create_time as ngay_dat_hang,
    DATETIME_ADD(vi.create_time, INTERVAL 7 HOUR) as ngay_hoan_thanh_thanh_toan,
    ord.hinh_thuc_thanh_toan as phuong_thuc_thanh_toan,
    '' as loai_don_hang,
    ord.doanh_thu_don_hang_uoc_tinh as doanh_thu_don_hang,
    ord.tong_tien_san_pham as tong_tien_san_pham,
    ord.so_tien_hoan_tra * -1 as so_tien_hoan_lai,
    ord.phi_van_chuyen_nguoi_mua_tra as phi_van_chuyen_nguoi_mua_tra,
    ord.phi_van_chuyen_thuc_te * -1 as phi_van_chuyen_thuc_te,
    ord.phi_van_chuyen_tro_gia_tu_shopee as phi_van_chuyen_tro_gia_tu_shopee,
    "" as phi_tra_hang,
    "" as phi_van_chuyen_duoc_hoan_tien,
    "" as phi_tra_hang_cho_nguoi_ban,
    ord.tro_gia_tu_shopee as tro_gia_tu_shopee,
    ord.voucher_from_seller * -1 as ma_giam_gia,
    "" as nguoi_ban_hoan_xu,
    ord.phi_co_dinh * -1 as phi_co_dinh,
    ord.phi_dich_vu * -1 as phi_dich_vu,
    ord.phi_thanh_toan * -1 as phi_thanh_toan,
    ord.phi_hoa_hong_tiep_thi_lien_ket * -1 as phi_hoa_hong_tiep_thi_lien_ket,
    ''as phi_dich_vu_piship,
    ''as thue_gtgt,
    ''as thue_tncn,
    ''as buyer_paid_installation_fee,
    ''as actual_installition_fee,
    ord.ten_nguoi_mua,
    ''as amount_paid_by_buyer,
    '' as transaction_fee_rate,
    '' as phuong_thuc_thanh_toan_nguoi_mua,
    ''as buyer_payment_method_details_1,
    '' as installment_plan,
    ''as phi_van_chuyen_seller_support,
    ord.ten_don_vi_van_chuyen,
    ''as couruer_name,
    ''as voucher_code,
    ''as den_bu_don_mat_hang,
    ''as gia_san_pham_sau_khuyen_mai,
    ''as shopee_xu,
    ''as shopee_voucher,
    ''as ngan_hang_khuyen_mai_the_tin_dung,
    ''as shopee_khuyen_mai_the_tin_dung
FROM {{ref("t1_shopee_shop_wallet_total")}} as vi
LEFT JOIN {{ref("t2_shopee_order_toa")}} as ord 
ON vi.order_id = ord.order_id AND vi.brand = ord.brand
where vi.transaction_tab_type = 'wallet_order_income'