SELECT
    create_time,
    brand,
    ten_nguoi_mua,
    hinh_thuc_thanh_toan,
    ten_don_vi_van_chuyen,
    ngay_ship,
    ly_do_huy_don,
    order_status,
    order_id,
    sum(day_to_ship) as day_to_ship,
    sum(test_doanh_thu) as test_doanh_thu,
    SUM(tong_tien_san_pham) AS tong_tien_san_pham,
    SUM(so_tien_hoan_tra) AS so_tien_hoan_tra,
    sum(phi_van_chuyen_nguoi_mua_tra) as phi_van_chuyen_nguoi_mua_tra,
    SUM(phi_van_chuyen_thuc_te) AS phi_van_chuyen_thuc_te,
    SUM(phi_van_chuyen_tro_gia_tu_shopee) AS phi_van_chuyen_tro_gia_tu_shopee,
    SUM(phi_co_dinh) AS phi_co_dinh,
    SUM(phi_dich_vu) AS phi_dich_vu,
    SUM(phi_thanh_toan) AS phi_thanh_toan,
    SUM(phi_hoa_hong_tiep_thi_lien_ket) AS phi_hoa_hong_tiep_thi_lien_ket,
    SUM(doanh_thu_don_hang_uoc_tinh) AS doanh_thu_don_hang_uoc_tinh,
    SUM(shopee_voucher) AS shopee_voucher,
    SUM(discount_from_coin) AS discount_from_coin,
    SUM(discount_from_voucher_seller) AS discount_from_voucher_seller,
    SUM(khuyen_mai_cho_the_tin_dung) AS khuyen_mai_cho_the_tin_dung,
    SUM(tong_tien_thanh_toan) AS tong_tien_thanh_toan,
    sum(tro_gia_tu_shopee) as tro_gia_tu_shopee
FROM {{ref("t2_shopee_order_lines_toa")}}
GROUP BY
    create_time,
    brand,
    ten_nguoi_mua,
    hinh_thuc_thanh_toan,
    ten_don_vi_van_chuyen,
    ngay_ship,
    ly_do_huy_don,
    order_status,
    order_id