SELECT
    brand AS `Brand`,
    COALESCE(order_id, adjustment_id) AS `Order adjustment ID`,
    type AS `Type`,
    FORMAT_TIMESTAMP('%Y/%m/%d', TIMESTAMP(order_create_time)) AS `Order created time`,
    FORMAT_TIMESTAMP('%Y/%m/%d', TIMESTAMP(statement_create_time)) AS `Order settled time`,
    statement_currency AS `Currency`,
    SAFE_CAST(settlement_amount AS FLOAT64) AS `Total settlement amount`,
    SAFE_CAST(revenue_amount AS FLOAT64) AS `Total revenue`,
    (SAFE_CAST(JSON_EXTRACT_SCALAR(revenue_breakdown, '$.subtotal_before_discount_amount') AS FLOAT64) + 
    SAFE_CAST(JSON_EXTRACT_SCALAR(revenue_breakdown, '$.seller_discount_amount') AS FLOAT64)) AS `Subtotal after seller discounts`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(revenue_breakdown, '$.subtotal_before_discount_amount') AS FLOAT64) AS `Subtotal before discounts`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(revenue_breakdown, '$.seller_discount_amount') AS FLOAT64) AS `Seller discounts`,
    (SAFE_CAST(JSON_EXTRACT_SCALAR(revenue_breakdown, '$.refund_subtotal_before_discount_amount') AS FLOAT64) + 
    SAFE_CAST(JSON_EXTRACT_SCALAR(revenue_breakdown, '$.seller_discount_refund_amount') AS FLOAT64)) AS `Refund subtotal after seller discounts`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(revenue_breakdown, '$.refund_subtotal_before_discount_amount') AS FLOAT64) AS `Refund subtotal before discounts`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(revenue_breakdown, '$.seller_discount_refund_amount') AS FLOAT64) AS `Refund of seller discounts`,
    SAFE_CAST(fee_tax_amount AS FLOAT64) AS `Total fees`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.transaction_fee_amount') AS FLOAT64) AS `Transaction fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(supplementary_component, '$.fbm_shipping_cost_amount') AS FLOAT64) AS `Seller shipping fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(shipping_cost_breakdown, '$.actual_shipping_fee_amount') AS FLOAT64) AS `Actual shipping fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(shipping_cost_breakdown, '$.supplementary_component.platform_shipping_fee_discount_amount') AS FLOAT64) AS `Platform shipping fee discount`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(shipping_cost_breakdown, '$.customer_paid_shipping_fee_amount') AS FLOAT64) AS `Customer shipping fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(supplementary_component, '$.retail_delivery_fee_refund_amount') AS FLOAT64) AS `Refund customer shipping fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(shipping_cost_breakdown, '$.return_shipping_fee_amount') AS FLOAT64) AS `Actual return shipping fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.platform_commission_amount') AS FLOAT64) AS `TikTok Shop commission fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(shipping_cost_breakdown, '$.supplementary_component.shipping_fee_subsidy_amount') AS FLOAT64) AS `Shipping fee subsidy`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.affiliate_commission_amount') AS FLOAT64) AS `Affiliate commission`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.affiliate_commission_amount_before_pit') AS FLOAT64) AS `Affiliate commission before PIT`,
    0.0 AS `Personal income tax withheld from affiliate commission`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.affiliate_ads_commission_amount') AS FLOAT64) AS `Affiliate Shop Ads commission`,
    0.0 AS `Affiliate Shop Ads Commission before PIT`,
    0.0 AS `Personal income tax withheld from affiliate Shop Ads commission`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.affiliate_partner_commission_amount') AS FLOAT64) AS `Affiliate partner commission`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.sfp_service_fee_amount') AS FLOAT64) AS `SFP service fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.live_specials_fee_amount') AS FLOAT64) AS `LIVE Specials Service Fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.voucher_xtra_service_fee_amount') AS FLOAT64) AS `Voucher Xtra Service Fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.flash_sales_service_fee_amount') AS FLOAT64) AS `Flash Sale service fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.fee.bonus_cashback_service_fee_amount') AS FLOAT64) AS `Bonus cashback service fee`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.tax.vat_amount') AS FLOAT64) AS `VAT withheld by TikTok Shop`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(fee_tax_breakdown, '$.tax.pit_amount') AS FLOAT64) AS `PIT withheld by TikTok Shop`,
    SAFE_CAST(adjustment_amount AS FLOAT64) AS `Adjustment amount`,
    order_id AS `Related order ID`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(supplementary_component, '$.customer_payment_amount') AS FLOAT64) AS `Customer payment`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(supplementary_component, '$.customer_refund_amount') AS FLOAT64) AS `Customer refund`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(supplementary_component, '$.seller_cofunded_discount_amount') AS FLOAT64) AS `Seller co-funded voucher discount`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(supplementary_component, '$.seller_cofunded_discount_refund_amount') AS FLOAT64) AS `Refund of seller co-funded voucher discount`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(supplementary_component, '$.platform_discount_amount') AS FLOAT64) AS `Platform discounts`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(supplementary_component, '$.platform_discount_refund_amount') AS FLOAT64) AS `Refund of platform discounts`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(supplementary_component, '$.platform_cofunded_discount_amount') AS FLOAT64) AS `Platform co-funded voucher discounts`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(supplementary_component, '$.platform_cofunded_discount_refund_amount') AS FLOAT64) AS `Refund of platform co-funded voucher discounts`,
    SAFE_CAST(JSON_EXTRACT_SCALAR(shipping_cost_breakdown, '$.supplementary_component.seller_shipping_fee_discount_amount') AS FLOAT64) AS `Seller shipping fee discount`,
    NULL AS `Estimated package weight`,
    NULL AS `Actual package weight`
FROM {{ ref('t1_tiktok_brand_statement_transaction_order_tot') }}